### PR TITLE
github.com/schneems -> github.com/zombocom [ci skip] 

### PR DESCRIPTION
**Pull request by dentarg**
I noticed that the repo had a new URL.

May I ask why? :)

### CODE REVIEW

**Comment by dentarg** [comment]
> May I ask why? :)

Something like https://github.com/sharpstone/rack-timeout/issues/145?

**Comment by dentarg** [comment]
Do you want this change in the changelog? 🤔

**Comment by schneems** [comment]
You can add `[ci skip]` to this PR title to skip the check.

I'm toying with the idea of moving some of my projects out of `schneems` namespace and adding some people on who might be willing or able to help maintain projects. individually there's not much to do, but when you add up all the projects there's a non-trivial maintenance burdeon. 

I'm not sure if it's a good idea or not, but I'm thinking about it. I've also owned this namespace forever and have never used it. I like that it's less specific than github.com/codetriage so it's not limited to just a specific subset of my projects.

**Comment by dentarg** [comment]
> You can add `[ci skip]` to this PR title to skip the check.

Done!

**Pull request merged**
